### PR TITLE
add validate_on_submit method

### PR DESCRIPTION
**Pull request by lixxu**
add `form.validate_on_submit` method, and set `self.app` again if app not pass to `__init__`

### CODE REVIEW

**Comment by pyx** [comment]
Nice catch on `self.app` part, I totally forgot about that since it's not been used after the call. Thank you.

Regarding the `validate_on_submit`, the reason why I did not include that it is because:
1. There is no such thing like thread-local objects (like the `request` in Flask and Bottle) in Sanic, (thanks to the async model, thread-local is not unique to each request), that's why we have to pass in the current `request` to make it work, I've been avoid doing this in Flask-WTF (and in Flask-CookieSession, and other things that I have not yet release publicly like templating, auth+auth, etc.), to my own taste, it doesn't look right (but I might be wrong), I think I need more input from all of you, since once we have that, we have to carry on with that API, unless we will gain a lot by doing so, so that brings the second point...
2. as of the implementation right now (nothing personal, I will come up the very same design if I decided to write it), we are actually not saving anything, line-count-wise, we have one-liner (test and test) vs one-liner (function call), but we pay for the function call, Sanic is a supposedly speedy creature, right?

Again, it is my personal opinion, please correct me if I am wrong.

@lixxu Do you mind draft a separate PR to correct the `self.app` part, so that I can merge that right away and have you credited?

Thank you so much.

**Comment by lixxu** [comment]
but imo, `validate_on_submit` is only a shortcut for `request.method == 'POST' and form.validate()`, if it has the thread-local issue, then the later way will have too.

**Comment by pyx** [comment]
@lixxu what I mean was:
The reason I did not implement `validate_on_submit`[1] myself to begin with, was in Sanic because of no reliable thread-local (that's why I mentioned it in last post), we have to have `validate_on_submit(request : sanic.Request) -> bool`, not just `validate_on_submit() -> bool`, and this API difference worries me (that's why I said I don't like it), it's not about thread-local issue, at least not directly related.

If later we find a way [2] to circumvent this, then we will create backward-incompatible upgrades, so, adding an API that will probably be changed later on, while that API does not help much (my whole point no. 2 in the last post, basically, it saves nothing and costs CPU cycles), in IMHO, it might not be a good idea to add `validate_on_submit` with signature different than what people may already be familiar with (like in Flask-WTF).

Criticisms are welcome.

[1] I am aware of it, I've been using Flask-WTF for a long time.
[2] Please see somewhat related issue #6 here, a possible way to solve this is to pass in `request` when initializing the `Form`, in that way, we can keep an alias of the current request, e.g. `self.request`, so parameter `request` on the call will not be required here.

PS. I have no problem with the `self.app` fix, if you could send a separate PR, I will merge it right away, it's unrelated to `validate_on_submit` anyway. Thank you.

**Comment by lixxu** [comment]
close for another PR.
btw, `keep an alias of the current request` seems make sense.

**Pull request closed without merging**
